name:                jni
version:             0.1.0
license:             BSD-2-Clause
author:
  - Tweag
maintainer:
  - Tweag
copyright:           "Tweag"
synopsis:            Call JNI from Haskell
category:            Bindings
description:         Please see the README.

flags:
  Cabal-syntax:
    description: Use the Cabal-syntax package for Cabal >= 3.8
    default: True

build-type: Custom
custom-setup:
  dependencies:
    - base
    - directory
    - filepath >= 1.4.2.2 && < 1.6
    - process
  when:
    - condition: flag(Cabal-syntax)
      then:
        dependencies:
          - Cabal >= 3.8
          - Cabal-syntax >= 3.8
      else:
        dependencies:
          - Cabal < 3.7
          - Cabal-syntax < 3.7

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - async
  - base
  - bytestring
  - choice
  - constraints
  - containers
  - deepseq
  - directory
  - errors
  - extra
  - inline-c
  - lens
  - mtl
  - newtype
  - pretty-simple
  - singletons-base
  - stm
  - template-haskell >= 2.18.0.0
  - text
  - transformers
  - unordered-containers

library:
  build-tool-depends: cpphs:cpphs
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -j4
  - -O2
  extra-libraries: jvm
  source-dirs:
    - src/common
  exposed-modules:
  - Foreign.JNI
  - Foreign.JNI.Internal
  - Foreign.JNI.String
  - Foreign.JNI.Types
  - Foreign.JNI.Unsafe
  - Foreign.JNI.Unsafe.Internal
  - Foreign.JNI.Unsafe.Internal.Introspection

tests:
  spec:
    main: Main.hs
    source-dirs:
      - tests
    dependencies:
      - hspec
      - jni
    ghc-options:
    - -threaded
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -j4
    - -O2
