name:                jvm
version:             0.1.0
license:             BSD-2-Clause
author:
  - Tweag
maintainer:
  - Tweag
copyright:           "Tweag"
synopsis:            Call JVM from Haskell
category:            Bindings
description:         Please see the README.

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base
  - bytestring
  - choice
  - constraints
  - distributed-closure
  - exceptions
  - jni
  - linear-base
  - singletons
  - template-haskell
  - text
  - vector

library:
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -j4
  - -O2
  source-dirs:
    - src/common
  exposed-modules:
  - Language.Java
  - Language.Java.Unsafe
  - Language.Java.Internal

tests:
  spec:
    main: Main.hs
    source-dirs:
      - tests
    dependencies:
      - hspec
      - jvm
      - QuickCheck
      - quickcheck-text
    ghc-options:
    - -threaded
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -j4
    - -O2
